name: 清除并移动文件

on: [push, pull_request]

jobs:
  clear-and-move:
    runs-on: ubuntu-latest

    steps:
    - name: 检出源代码
      uses: actions/checkout@v2

    - name: 清空public目录
      run: |
        # 删除public目录下的所有文件和文件夹
        rm -rf public/*

    - name: 从.vitepress/dist/移动文件到public/
      run: |
        # 检查.vitepress/dist目录是否存在
        if [ -d ".vitepress/dist/" ]; then
          # 移动.vitepress/dist目录下的所有文件和文件夹到public目录
          mv .vitepress/dist/* public/
        else
          echo "错误：.vitepress/dist/目录不存在。"
          exit 1
        fi